name: Run Benchmarks

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the 1st of every month

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # ,  windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11" 
          miniconda-version: "latest"
      - name: Downgrade conda
        run: conda install conda=24.1
        shell: bash
      - name: Install package with pip
        run: |
          pip install .
        shell: bash
      - name: Install ASV
        run: |
          pip install asv
        shell: bash
      - name: Run ASV benchmarks
        run: |
          asv machine --yes
          asv run HASHFILE:hashestobenchmark.txt

      - name: Push ASV results to gh-pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git fetch
          git pull
          asv publish
          asv gh-pages
