name: Run Benchmarks

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the 1st of every month

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 12  # Adjust Python version as needed

      - name: Install package with pip
        run: pip install -e .

      - name: Run ASV benchmarks
        run: asv run HASHFILE:hashestobenchmark.txt

      - name: Push ASV results to gh-pages
        run: asv gh-pages
